### ISSUE TITLE
Is it possible to modify the code to generate QR Code with data up to 10k

### ISSUE THREAD

**Issue by malhobayyeb** [nayuki/Fast-QR-Code-generator#2]
I have a use case where I have to store 10k of data in a QR Code.

Can this be achieved with your library after modifications?

**Comment by nayuki** [comment]
A single QR Code symbol stores at most 2953 bytes of data. If you need to store more than that, you should look at the "Structured Append" feature to spread the data out over multiple QR Codes. My library does not support this feature. It could be implemented with significant modifications, which I'm not offering.
