### ISSUE TITLE
want to generate a different Image than a QR code.

### ISSUE THREAD

**Issue by rkumarsingh007** [nayuki/Fast-QR-Code-generator#3]
i want to generate a different image than a qr code. so that the data inside the qr code could not get reviled. and the organization software could only scan it. not any other qr code scanner. is it possible to do some changes in your source code and obtain the objective.

or you may provide me with an a bit simpler way to do so. it would be very much helpful.

**Comment by suryabhairaj** [comment]
please comment i am waiting ...
